# Version
version: '3.8'

services:
  # web:
  #   container_name: web_spardacms
  #   build:
  #     context: ./
  #     dockerfile: docker/web.dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app
  #   networks:
  #     - spardacms_network

  app:
    container_name: app_spardacms
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    ports:
        - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - spardacms_network
  
networks:
  spardacms_network:
    name: spardacms_network