# Version
version: '3.8'

services:
  # web:
  #   container_name: web_spardacms
  #   build:
  #     context: ./
  #     dockerfile: docker/web.dockerfile
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - fpm
  #   networks:
  #     - spardacms_network
  #   volumes:
  #     - ./:/var/www/html

  app:
    container_name: app_spardacms
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    ports:
        - "127.0.0.3:80:80"
    depends_on:
      - fpm
    networks:
      - spardacms_network
    volumes:
      - ./:/var/www/html

  fpm:
    container_name: fpm_spardacms
    build:
      context: ./
      dockerfile: docker/fpm.dockerfile
    networks:
      - spardacms_network
    volumes:
      - ./:/var/www/html
  
networks:
  spardacms_network:
    name: spardacms_network